// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyyBPaNXgE05kxr2LprlMuWrFkvBhyP1k',
    appId: '1:835192150682:web:41b6b9b1aed6b1bc88dd23',
    messagingSenderId: '835192150682',
    projectId: 'fir-crud-36f00',
    authDomain: 'fir-crud-36f00.firebaseapp.com',
    storageBucket: 'fir-crud-36f00.firebasestorage.app',
    measurementId: 'G-5G2NTSFTG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApFmP-s4zHYJ2D_GlXAWQifsAc2OLlGBc',
    appId: '1:835192150682:android:2b923c419e462cac88dd23',
    messagingSenderId: '835192150682',
    projectId: 'fir-crud-36f00',
    storageBucket: 'fir-crud-36f00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCuVvAApeMJwjjGzGNamiuqR2xeSZ0tIQ',
    appId: '1:835192150682:ios:3263ff8a3ae06e2788dd23',
    messagingSenderId: '835192150682',
    projectId: 'fir-crud-36f00',
    storageBucket: 'fir-crud-36f00.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
